CREATE TABLE IF NOT EXISTS filiale (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codice VARCHAR(20) NOT NULL UNIQUE,
  indirizzo VARCHAR(255) NOT NULL,
  citta VARCHAR(100) NOT NULL,
  cap VARCHAR(10) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);