CREATE TABLE IF NOT EXISTS automezzo (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codice VARCHAR(20) NOT NULL UNIQUE,
  targa VARCHAR(15) NOT NULL UNIQUE,
  marca VARCHAR(50) NOT NULL,
  modello VARCHAR(50) NOT NULL,
  filiale_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (filiale_id) REFERENCES filiale(id) ON DELETE RESTRICT
);